### ISSUE TITLE
labels for the parameters are obscure

### ISSUE THREAD

**Issue by derrickhatcher** [econ-ark/Pandemic#8]
Even for a very technical subject of interest to a relatively small community the labels for the sliders are particular obscure.  Matching the parameters in the simulation to those in the paper is challenging.

**Comment by mnwhite** [comment]
We can try to add a correspondence for each label, but I'm not sure if LaTeX can render in the dropdown menu.  We'll try.

**Comment by mnwhite** [comment]
Also, a small number of parameters in the menu *don't* have an analog in the paper-- they're features in the code that we didn't discuss in the paper.  In particular, households' perceptions/beliefs about transition probabilities and the *actual* transition probabilities may differ.

**Comment by llorracc** [comment]
Resolved by a merge a few months ago.
